### ISSUE TITLE
Can you make a smartphone-friendly version?

### ISSUE THREAD

**Issue by Mira217** [expfactory-experiments/digit-span#1]
Hi, I am intending to use this for my experiment. However, there is 1 section that says "press enter to start" which is inexecutable in smartphones. Is there any quick way to remove that screen so that subjects can access the game from their phone?
One more thing, I know I am asking too much but maybe you can give me some pointers here (I am new to javascript). I noticed in your code, you can store the score of the subjects, but it seems like the version we have will keep looping indefinitely. Is there a way to "end" the game and print out the "score" of the player?

Many thanks!

**Comment by vsoch** [comment]
hey Mira! A smartphone version can work fairly easily if you add css to the styling to handle different media sizes. I think this would be better than to remove the prompt entirely, do you agree? Here is how we can figure out what to do!

 - We can see the experiment running [on its preview page](https://expfactory-experiments.github.io/digit-span/)
 - We can input it into a side to preview on [mobile](https://ready.mobi/#946162-uiyo). 

Can you tell me what dimensions you re having trouble with?

When you install the experiment via the expfactory container, it shouldn't loop forever. Is this how you re running it (or some other way?)

**Comment by vsoch** [comment]
And I didn't answer your question! For different devices needs, what I usually see is handling via the css media property. Here is a good [example](https://www.w3schools.com/css/css3_mediaqueries_ex.asp). So what we would want to do is identify the dimensions causing trouble, and then add media sections to the css file to handle (and test them out).

**Comment by Mira217** [comment]
Many thanks for the reply vsoch! I am trying that now, actually I did not know it has to be run via a container.

**Comment by vsoch** [comment]
Technically, you could finagle running it without a container, as it runs as a static experiment (e.g., the one on Github pages) but you would need to set up your own method to collect and save results. The container approach is recommended because it also makes your experiment reproducible! If someone needs to run exactly as you did, they just run the container :)
